### ISSUE TITLE
 IEntityTypeBuilder<TEntity>.Entity<TEntity> automatically creates FieldMetadata for primitive field in Base class

### ISSUE THREAD

**Issue by mrt181** [tomasfabian/ksqlDB.RestApi.Client-DotNet#102]
**Describe the bug**
I am using the modelbuilder to flag a field as a pseudo column that is defined as a primitive type on a the base class.

When that field is not nullable the builder contains a default definition for that field when the builder is instantiated.

When that field is nullable the builder does not contain a default definition for that field when the builder is instantiated.
**To Reproduce**
```csharp
public class Row
{
  public long? RowOffset { get; set; }
  public short? RowPartition { get; set; }
  public long RowTime { get; set; }
}

public class MyValue : Row
{
  public int Id { get; set; }
}

var builder = new ModelBuilder();
builder.Entity<MyValue>().Property(p => p.RowTime).AsPseudoColumn();
```
**Expected behavior**
I expect the fieldMetadata for RowTime to be in the builder with the correct settings.

**Screenshots**
This is when the Entity is created
![image](https://github.com/user-attachments/assets/92e1f725-61f4-4eef-b1d6-2e8027f93a95)
It already contains the `RowTime` field.

This is after adding the `RowTime` and flagging it as a pseudo-column.
![image](https://github.com/user-attachments/assets/8d5f2870-a4ca-40ec-b731-94c6ef1e1e19)
The field is defined twice now.

**Environment (please complete the following information):**
 - `ksqlDb` version: `7.7.1`
 - `ksqlDb.RestApi.Client` Nuget package version `6.5.0`
 - TFM [net8.0]

**Additional context**

**Comment by tomasfabian** [comment]
Hello Martin, I prepared a hot fix #103.

**Comment by tomasfabian** [comment]
I released a hotfix:
```cmd
NuGet\Install-Package ksqlDb.RestApi.Client -Version 6.5.1
```

**Comment by mrt181** [comment]
The hotfix works.
