### ISSUE TITLE
ConsumeAsync is not responding on CancellationToken (while waiting on ReadLineAsync)

### ISSUE THREAD

**Issue by ArnoRienstra** [tomasfabian/ksqlDB.RestApi.Client-DotNet#25]
**Describe the bug**
KSQL-queries are not removed from KSQL if nothing received after cancelling.
CreateQueryStream is calling ConsumeAsync, which is not responding on CancellationToken (while waiting on EndOfStream or ReadLineAsync)

**To Reproduce**
After creating a push query using a filter on a certain ID, the ksql query is not removed from ksql if no new information is streamed.
In our case, if a device is stopped or removed, there is no new record published and as such the library is waiting in ReadLineAsync.
After initiating a new record the EndOfstream is continued and cancellation performed thereafter and as such ksql-query cancelled in ksql.

**Expected behavior**
Perhaps exception is to be raised on thread from cancellationtoken, being handled by the ConsumeAsync?
When .NET7 is released, use the cancellationtoken in the ReadLineAsync?

**Environment (please complete the following information):**
 - ksqldb version: 0.21.0
 - ksqlDB.RestApi.Client: 2.1.0
 - TFM: .NET 6

**Comment by tomasfabian** [comment]
Hi @ArnoRienstra,
this is really unfortunate. Hopefully the .NET team will add a `EndOfStreamAsync` + `ReadLineAsync` which can accept a `CancellationToken`.

Could you help me to find a suitable solution, please? What do you think about registering an action for the cancellationToken in the following way?

```C#
    public async IAsyncEnumerable<T> Run<T>(object parameters, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
      logger?.LogInformation($"Executing query {parameters}");

      using var streamReader = await TryGetStreamReaderAsync<T>(parameters, cancellationToken).ConfigureAwait(false);

      cancellationToken.Register(() =>
      {
        semaphoreSlim.Release();
      });

      await foreach (var entity in ConsumeAsync<T>(streamReader, cancellationToken).WithCancellation(cancellationToken).ConfigureAwait(false))
        yield return entity;
    }

    private Task<bool> EndOfStreamAsync(StreamReader streamReader, CancellationToken cancellationToken)
    {
      return Task.Run(() =>
      {
        try
        {
          return !streamReader.EndOfStream;
        }
        catch (Exception e)
        {
          if (!cancellationToken.IsCancellationRequested)
            throw e;

          return true;
        }

      }, cancellationToken);
    }

    private async IAsyncEnumerable<T> ConsumeAsync<T>(StreamReader streamReader, [EnumeratorCancellation] CancellationToken cancellationToken)
    {
      var cancellationTask = Task.Run(() =>
      { 
        semaphoreSlim.Wait();
        return false;
      }, cancellationToken);

      while (await await Task.WhenAny(EndOfStreamAsync(streamReader, cancellationToken), cancellationTask))
      {
        if (cancellationToken.IsCancellationRequested)
          yield break;

        var rawData = await streamReader.ReadLineAsync()
          .ConfigureAwait(false);

        logger?.LogDebug($"Raw data received: {rawData}");

        var record = OnLineRead<T>(rawData);

        if (record != null) yield return record.Value;
      }
    }
```

Could you evaluate/test the above solution, please? Is `streamReader.ReadLineAsync()` still blocking?
If you can come up with a better solution please let me know.

Thank you!
Regards Tomas.

**Comment by ArnoRienstra** [comment]
Hello Tomas,

Thank you for the swift response!

This seems to do the job and we can not think of a cleaner solution while .net framework does not support this in ReadLineAsync natively. We'll look out for the next package update,

Thanks again,

Regards,
Arno

**Comment by tomasfabian** [comment]
Hi @ArnoRienstra,
I published a new package version 2.1.2 with the fix.  

Let me know if everything is OK.

Thanks too.

Regards Tomas.

**Comment by ArnoRienstra** [comment]
Hello Tomas,

Thanks for your effort updating the package, 

We updated to this release for closing the issue but there seems to be an issue with the .NET version.
Now the .NET version 6 is included in the project file, then the conditional statement in KSqlDbQueryStreamProvider should be changed from #if NET5_0 to #if NET5_0_OR_GREATER. This appears to be a breaking change for us and perhaps other users.

https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/blob/290c354556c04888e36066da64bc92fd5ab4e58f/ksqlDb.RestApi.Client/KSql/RestApi/KSqlDbQueryStreamProvider.cs#L68

Regards,
Arno

**Comment by ArnoRienstra** [comment]
Yes please, no problem!

**Comment by ArnoRienstra** [comment]
It's working as expected now, thanks!
