### ISSUE TITLE
RowValueJsonSerializer.Deserialize<byte[]> fails

### ISSUE THREAD

**Issue by woutersmit** [tomasfabian/ksqlDB.RestApi.Client-DotNet#35]
**Describe the bug**
Deserialization of rawJson to byte[] fails since v2.5.1 (commit a0da7784baa4f12f58768db8f3a17280540016ba)

**To Reproduce**
```
  [TestMethod]
  public void Deserialize_RecordAsByteArray()
  {
    //Arrange
    var queryStreamHeader = new QueryStreamHeader()
    {
      ColumnTypes = new[] { "MESSAGE" },
      ColumnNames = new[] { "BYTES" },
    };

    ClassUnderTest = new RowValueJsonSerializer(queryStreamHeader);
    
    string rawJson = "[\"e30=\"]";
    var jsonSerializationOptions = KSqlDbJsonSerializerOptions.CreateInstance();

    //Act
    var rowValue = ClassUnderTest.Deserialize<byte[]>(rawJson, jsonSerializationOptions);

    //Assert
    rowValue.Value.Should().BeOfType<byte[]>();
    rowValue.Value[0].Should().Be(0x7b);
    rowValue.Value[1].Should().Be(0x7d);
  }
```

**Expected behavior**
Serialization of byte[] conform unittest above

**Screenshots**
-

**Environment (please complete the following information):**
 - ksqldb version: 0.28.2
 - ksqlDB.RestApi.Client nuget package version 2.5.1
 - net6.0

**Comment by tomasfabian** [comment]
Hi @woutersmit,
could you please review [this PR](https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/pull/36) please?

Thank you!

**Comment by woutersmit** [comment]
Placed one comment. Rest LFTM.
