### ISSUE TITLE
Support for passing sessionVariables 

### ISSUE THREAD

**Issue by MikeHixsonSdc** [tomasfabian/ksqlDB.RestApi.Client-DotNet#39]
Hello,

I'm wondering if there is a way to pass `sessionVariables` to the /ksql endpoint using `KSqlDbRestApiClient`? I assumed this would be possible via `KSqlDbStatement`, but I did not see any members for this.

**Comment by tomasfabian** [comment]
Hi @MikeHixsonSdc,
I [created a PR](https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/pull/40) for the requested feature. Could you please review it?

Thank you in advance.

Regards Tomas

**Comment by tomasfabian** [comment]
I've just realesed a new version with the above mentioned feature. Enjoy it!

```
dotnet add package ksqlDb.RestApi.Client --version 2.6.0
```
