### ISSUE TITLE
Predicate with .Equals fails.

### ISSUE THREAD

**Issue by bmmptlgc** [tomasfabian/ksqlDB.RestApi.Client-DotNet#50]
String comparison using "==" in a predicate like `.Where(item => item.stringField == "some string")` translates to `WHERE stringField == "some string"` but `.Where(item => item.stringField.Equals("some string"))` fails.

**Comment by tomasfabian** [comment]
Hello @bmmptlg,
I published a new package version with the requested functionality.

```
dotnet add package ksqlDb.RestApi.Client --version 3.4.0
```

Regards Tomas

**Comment by bmmptlgc** [comment]
Thanks for the quick implementation.
