### ISSUE TITLE
Predicate with .StartsWith fails.

### ISSUE THREAD

**Issue by bmmptlgc** [tomasfabian/ksqlDB.RestApi.Client-DotNet#51]
String comparison using `.Where(item => item.stringField.StartsWith("some string"))` fails. It would be nice if it translated to `WHERE instr(stringField, 'some string') > 0`.

**Comment by tomasfabian** [comment]
Hi @bmmptlgc,
the above predicate should be translated to `WHERE stringField LIKE 'some string%'`. Could you provide more details, please?

**Comment by bmmptlgc** [comment]
It seems to be that ksql doesn't support `AND` and  `LIKE` on the same query.
![image](https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/assets/109662343/7dcf02f7-f214-4f6a-b216-5d11c1cc2dbe)

**Comment by tomasfabian** [comment]
It seems you've come across this [ksql issue](https://github.com/confluentinc/ksql/issues/8359). I tested it with streams, and it behaves as anticipated. Could be the below approach a viable workaround for you until the issue is addressed in `ksqldb`?

```C#
using  ksqlDB.RestApi.Client.KSql.Query.Functions;

.Where(item => K.Functions.Instr(item.stringField, "some string") > 0)
```

**Comment by bmmptlgc** [comment]
That works perfectly, thank.
