### ISSUE TITLE
Execution of pull query use a wrong table name

### ISSUE THREAD

**Issue by draudrau** [tomasfabian/ksqlDB.RestApi.Client-DotNet#52]
**Describe the bug**
Issue when using the `KSqlDBContext.CreatePullQuery()` function.
The value given to the `tableName` parameter is not use as is.
The table name in the underlying SQL query has an additional 'S' character.
The table name doesn't follow the name gave in the `KSqlDBContext.CreateOrReplaceTableStatement("TABLE_NAME")` function.

**To Reproduce**
- create a topic
- create a table on this topic with `KSqlDbRestApiClient.CreateOrReplaceTableAsync()`
- create a table statement on this topic with  `KSqlDBContext.CreateOrReplaceTableStatement("TABLE_NAME")` 
- execute a pull query with `KSqlDBContext.CreatePullQuery<TableType>("TABLE_NAME")`

The SQL produce contains a wrong table name : TABLE_NAME**S**
The execution produce an exception :
`ksqlDB.RestApi.Client.KSql.RestApi.Exceptions.KSqlQueryException : Exception while preparing statement: TABLE_NAMES does not exist.`

**Expected behavior**
The table name must exactly follow the given parameter in the pull query : TABLE_NAME

**Environment (please complete the following information):**
 - `ksqlDb` version: 7.5.2
 - `ksqlDb.RestApi.Client` Nuget package version: 3.4.0
 - net8.0

**Comment by tomasfabian** [comment]
Hello @draudrau,
you have the option to configure the table name to be singular, as demonstrated below:

```C#
using ksqlDB.RestApi.Client.KSql.Linq;
using ksqlDB.RestApi.Client.KSql.Query;
using ksqlDB.RestApi.Client.KSql.Query.Context;
using ksqlDB.RestApi.Client.KSql.Query.Options;

var ksqlDbUrl = @"http://localhost:8088";

var contextOptions = new KSqlDBContextOptions(ksqlDbUrl)
{
  ShouldPluralizeFromItemName = false
};

await using var context = new KSqlDBContext(contextOptions);
```

**Comment by draudrau** [comment]
I missed this setting.
Thank you for the info.
