### ISSUE TITLE
How to perform EXPLODE on a generic array?

### ISSUE THREAD

**Issue by vnkkarpenko** [tomasfabian/ksqlDB.RestApi.Client-DotNet#54]
Hi,
I have a question how to group the Id and DetailId fields to get the final price and quantity values without subscribing so that the data aggregation is done only on ksqldb?

Thank you!

my models:
```c#
public class SalesAggregatedModel
{
    public string Version { get; set; }
    public SalesHeadModel Head { get; set; }
    public List<SalesDetailsModel> Details { get; set; }
}

public class SalesHeadModel
{
    [Key]
    public int Id { get; set; }
    public string StreamType { get; set; }
}

public class SalesDetailsModel
{
    public int DetailId { get; set; }
    public double Quantity { get; set; }
    public double Price { get; set; }
    public string Date { get; set; }
}

**Comment by tomasfabian** [comment]
Hello @vnkkarpenko,
are you asking for an integration of the [Explode table](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/table-functions/#explode) function in `ksqlDb.RestApi.Client`?

**Comment by vnkkarpenko** [comment]
> Hello @vnkkarpenko, are you asking for an integration of the [Explode table](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/table-functions/#explode) function in `ksqlDb.RestApi.Client`?

Hello @tomasfabian, 
It will probably take a long time to integrate, maybe there is an analogue of this function or another solution to get a similar result?

**Comment by tomasfabian** [comment]
This dynamic approach could function as a temporary workaround until I incorporate type-safe support for the `Explode` function:
https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/blob/main/docs/functions.md#dynamic---calling-not-supported-ksqldb-functions

**Comment by vnkkarpenko** [comment]
Thank you!

**Comment by tomasfabian** [comment]
Hello @vnkkarpenko,
you can use the `Explode` table function with `ksqlDb.RestApi.Client`  v3.5.0 in the following manner.
```C#
using ksqlDB.RestApi.Client.KSql.Query.Functions;

Select(l => new { Result = l.Details.Explode() })
```

**Comment by vnkkarpenko** [comment]
Hello @tomasfabian,
Thank you very much!
