### ISSUE TITLE
How can I use enums on my data types when creating streams / tables?

### ISSUE THREAD

**Issue by mrt181** [tomasfabian/ksqlDB.RestApi.Client-DotNet#55]
I deriving code from a json-schema. The schema defines string properties with a few enum values.

These are code generated into csharp enums.

When I create a statement.
```csharp
 var metadata = new EntityCreationMetadata
    {
      KafkaTopic = "Test",
      EntityName = "Test",
      Partitions = 1,
      Replicas = 1,
      ValueFormat = SerializationFormats.Json,
    };
    var createOrReplaceTableStatement = StatementGenerator.CreateOrReplaceTable<TestClass>(metadata);
```
I get this output:
```sql
CREATE OR REPLACE TABLE Test (
        node STRUCT<Id BIGINT, Name VARCHAR, Type >,
        limits ARRAY<STRUCT<End TIMESTAMP, Max BIGINT, Min BIGINT, Period , Start TIMESTAMP>>,
        direction ,
        end TIMESTAMP,
        id VARCHAR PRIMARY KEY,
        start TIMESTAMP
) WITH ( KAFKA_TOPIC='Test', VALUE_FORMAT='Json', PARTITIONS='1', REPLICAS='1' );
```
All the enum fields do not have a type attached to them.
I have attached the `Struct` annotation to the classes that are object properties in the schema but this does not work for the enums. How can I map enums as STRING / VARCHAR?

**Comment by mrt181** [comment]
On the creation side this might do it?
```csharp
    internal static string KSqlTypeTranslator(Type type)
    ...
    else if (!type.IsGenericType && (type.IsClass || type.IsStruct()))
     {
       str1 = type.Name.ToUpper();
     }
     else if (type.IsEnum)
     {
       str1 = "VARCHAR";
     }
     else
     ...
```
Treating the column values as strings because they will be strings in the underlying json data.
When reading them they need to be parsed back into the enum though.

**Comment by mrt181** [comment]
I am looking into it.

I cloned the project into linux/WSL and had to update the project references to fix the build like this:
[test-csproj.patch](https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/files/14357669/test-csproj.patch)

There are two equal project files that only differ by their names, I guess it just works in windows because they are treated as the same thing?
[ksqlDB.RestApi.Client.csproj](https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/blob/main/ksqlDb.RestApi.Client/ksqlDB.RestApi.Client.csproj)
[ksqlDb.RestApi.Client.csproj](https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/blob/main/ksqlDb.RestApi.Client/ksqlDb.RestApi.Client.csproj)

**Comment by tomasfabian** [comment]
I haven't noticed it thus far. I removed `ksqlDB.RestApi.Client.csproj` in the feature branch. Thx!

If it's more convenient for you, I can also publish a release candidate on NuGet.

**Comment by mrt181** [comment]
I had to fix three tests to use `Environment.NewLine`
[parsertests-newline.patch](https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/files/14358281/parsertests-newline.patch)

**Comment by tomasfabian** [comment]
`dotnet add package ksqlDB.RestApi.Client --version 3.6.0-rc.1`

**Comment by tomasfabian** [comment]
I applied all your changes. Thank you for the feedback so far @mrt181.

**Comment by tomasfabian** [comment]
Did you mean that the changes could be merged into the main branch, or were you referring to just using the package instead of cloning the repository works?

**Comment by mrt181** [comment]
From my pov this can be merged into main

**Comment by tomasfabian** [comment]
I merged it :) Thank you very much for this enhancement and your improvements!

**Comment by tomasfabian** [comment]
@mrt181 
I've created a [Vagrant file](https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/blob/main/Vagrantfile) tailored for Linux development on a Windows environment. My next step is to adapt the tests for seamless execution across different operating systems.

**Comment by tomasfabian** [comment]
Hello @mrt181, I resolved the issues with the unit tests to ensure compatibility with Linux systems.
