### ISSUE TITLE
JsonPropertyNames are ignored when using syntax to select individual columns.

### ISSUE THREAD

**Issue by mrt181** [tomasfabian/ksqlDB.RestApi.Client-DotNet#61]
**Describe the bug**
JsonPropertyNames are ignored when using syntax to selec individual columns.

**To Reproduce**
```csharp
  public class JsonPropertyNameTestData
  {
    [JsonPropertyName("sub")] public SubProperty SubProperty { get; set; }
  }

  [Struct]
  public class SubProperty
  {
    [JsonPropertyName("prop")] public string Property { get; set; }
  }

  [Test]
  public void SelectColumnsUsingPullQueryThatHaveJsonPropertyName()
  {
    //Arrange
    //Act
    var ksql = DbProvider.CreatePullQuery<JsonPropertyNameTestData>()
      .Select(c => new { c.SubProperty })
      .ToQueryString();

    //Assert
    ksql.Should().BeEquivalentTo(
      @$"SELECT sub FROM {nameof(JsonPropertyNameTestData)};".ReplaceLineEndings());
  }

  [Test]
  public void SelectColumnsUsingPullQueryThatHaveJsonPropertyNameWithAlias()
  {
    //Arrange
    //Act
    var ksql = DbProvider.CreatePullQuery<JsonPropertyNameTestData>()
      .Select(c => new { Prop = c.SubProperty })
      .ToQueryString();

    //Assert
    ksql.Should().BeEquivalentTo(
      @$"SELECT sub As Prop FROM {nameof(JsonPropertyNameTestData)};".ReplaceLineEndings());
  }
```

**Expected behavior**
Both Tests should work but only the second one with the alias does.
The first one uses `SubProperty` as column name. 

**Environment (please complete the following information):**
 - `ksqlDb` version: 7.6.0
 - `ksqlDb.RestApi.Client` Nuget package version 3.6.1]
 - TFM net8.0

**Additional context**
This is needed when selecting `PseudoColumns` like `ROWTIME` but will fail because a stream / table creates the column names using the `JsonPropertyNames`

**Comment by mrt181** [comment]
These are the places that seem related to this but I have currently no idea how to fix this. The moment I touch it many tests that use column selection syntax break.
![Screenshot 2024-03-05 113115](https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/assets/161961/72a75912-d193-4346-a1dc-30ff709835ec)
![Screenshot 2024-03-05 113041](https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/assets/161961/5c5cdfee-c0a4-42de-87ef-acda18d2e8ef)

**Comment by tomasfabian** [comment]
Do we want to implement the suggested fix mentioned above? If so, I can prepare a pull request (PR), or would you prefer to handle it yourself?

**Comment by mrt181** [comment]
I did an additional change to cover pseudocolumns and added some tests. If ok than I will create a PR.

**Comment by tomasfabian** [comment]
Thank you @mrt181 for the PR! I released a patch:
```
dotnet add package ksqlDb.RestApi.Client --version 3.6.2
```
