### ISSUE TITLE
Package 4.0.0 that is mentioned in README is not released.

### ISSUE THREAD

**Issue by mrt181** [tomasfabian/ksqlDB.RestApi.Client-DotNet#67]
The package version `4.0.0` that is mentioned in the README is not available as a nuget package on nuget.org.

The last version on [nuget.org](https://www.nuget.org/packages/ksqlDb.RestApi.Client/4.0.0-rc.4#versions-body-tab) is `4.0.0-rc.4`

**Comment by tomasfabian** [comment]
Hi @mrt181,
I've just released it.
