### ISSUE TITLE
c# decimal is mapped to STRUCT type.

### ISSUE THREAD

**Issue by mrt181** [tomasfabian/ksqlDB.RestApi.Client-DotNet#81]
**Describe the bug**
When I define a Property like this:
```csharp
[JsonPropertyName("volume")]
[Decimal(20,8)]
public decimal Volume { get; set; }
```
The created statement during an insert uses this type
```sql
`volume` := STRUCT()
```
The `volume` property is within an `ARRAY[STRUCT()]` type that itself is within an `ARRAY[STRUCT]` type.
When I change the property type to `double` it uses the `DECIMAL(20,8)` in the insert statement.

**Expected behavior**
The `DECIMAL(20,8)` type should be used when the property has that attribute even when its c# type is `decimal`. 

**Environment (please complete the following information):**
 - `ksqlDb` version: `v7.6.0`
 - `ksqlDb.RestApi.Client` Nuget package version `v6.0.1`
 - TFM `net8.0`

**Comment by mrt181** [comment]
> Hi @mrt181, could you please confirm that the expected generated KSQL statement should match the following?
> 
> ```sql
> INSERT INTO Amounts (volume) VALUES (1.12345678912345);
> ```
That's correct the current implemenation creates this:
```sql
INSERT INTO Amounts (volume) VALUES (STRUCT());
```
While it also creates this table definition:
```chsharp
    string createTable = new StatementGenerator().CreateTable<Amount>(metadata);
```
```sql
CREATE TABLE `Amounts` (
	`volume` DECIMAL(20,8)
) WITH ( KAFKA_TOPIC='amounts', VALUE_FORMAT='Json', PARTITIONS='1', REPLICAS='1' );
```

**Comment by tomasfabian** [comment]
I published a hot fix:
```cmd
dotnet add package ksqlDb.RestApi.Client --version 6.0.2
```
