### ISSUE TITLE
Regression of issue #68

### ISSUE THREAD

**Issue by mrt181** [tomasfabian/ksqlDB.RestApi.Client-DotNet#84]
**Describe the bug**
see issue #68

**To Reproduce**
see issue #68

**Expected behavior**
see issue #68

**Environment (please complete the following information):**
 - `ksqlDb` version: [7.6.0]
 - `ksqlDb.RestApi.Client` Nuget package version [6.0.2, 6.1.0]
 - TFM [net8.0]

**Additional context**
The workaround mentioned in #68 still works

**Comment by tomasfabian** [comment]
Hello @mrt181,
could you provide a test case, please? The [existing test](https://github.com/tomasfabian/ksqlDB.RestApi.Client-DotNet/blob/main/Tests/ksqlDB.RestApi.Client.Tests/KSql/Linq/PullQueries/PullQueryExtensionsTests.cs#L233) passes, but probably additional coverage is needed.

Thank you!

**Comment by tomasfabian** [comment]
Hi @mrt181, could you please help me reproduce this issue?

**Comment by mrt181** [comment]
Sorry, for coming back so late to this. I was away.
I can not reproduce this anymore.
