### ISSUE TITLE
Specify IgnoreInDDL using both the model builder and the attribute.

### ISSUE THREAD

**Issue by tomasfabian** [tomasfabian/ksqlDB.RestApi.Client-DotNet#93]
To exclude fields that are not supported for CREATE statements but allowed in INSERT statements, such as the `RowTime` pseudo column, a new function `IgnoreInDDL` should be introduced using the model builder, along with a corresponding attribute. Here's an example of how this can be implemented:

```C#
modelBuilder.Entity<Record>()
    .Property(r => r.RowTime)
    .IgnoreInDDL(); // This will exclude RowTime from CREATE but allow it in INSERT
```

```C#
[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
public class IgnoreInDDLAttribute : Attribute
{
}
```

**Comment by mrt181** [comment]
Should this be a public API? 🤔

It only applies to `RowTime`, the only pseudo column that can be inserted into.

As a general API it will lead to errors for any other column definition.

The current implementation already ignores all pseudo columns in DDL Statements.

**Comment by tomasfabian** [comment]
I changed it to an internal implementation as you suggested see #94. Thank you @mrt181!

**Comment by tomasfabian** [comment]
A new version is available. Thanks a lot, @mrt181.
```
dotnet add package ksqlDb.RestApi.Client --version 6.4.0
```
